#define SNAPSHOT_BTN		PIN_A0
#define JOYSTICK0			PIN_A1
#define JOYSTICK1			PIN_A2
#define JOYSTICK2			PIN_A3
#define JOYSTICK3			PIN_A4
#define JOYSTICK4			PIN_A5
#define NC_A6				PIN_A6
#define NC_A7				PIN_A7

#define	INITIAL_PORTA_VALUE	0b00000000
#define	INITIAL_TRISA_VALUE	0b11111111

#define PS2_CLK0			PIN_B0
#define PS2_CLK1			PIN_B1
#define PS2_DATA0			PIN_B2
#define PS2_DATA1			PIN_B3
#define KEYBOARD_LED		PIN_B4
#define MOUSE_LED			PIN_B5
#define ICD_PGC				PIN_B6
#define ICD_PGD				PIN_B7

#define	INITIAL_PORTB_VALUE	0b00110000
#define	INITIAL_TRISB_VALUE	0b11001111

#define RESTORE				PIN_C0
#define PADDLE1				PIN_C1
#define PADDLE2				PIN_C2
#define JOYSWITCH_INHIBIT	PIN_C3
#define JOYSWITCH_SELECT	PIN_C4
#define CBM_RESET_LINE		PIN_C5
#define SER_TX				PIN_C6
#define SER_RX				PIN_C7

#define	INITIAL_PORTC_VALUE	0b00000000
#define	INITIAL_TRISC_VALUE	0b11100111

#define CROSSPOINT_AY0		PIN_D0
#define CROSSPOINT_AY1		PIN_D1
#define CROSSPOINT_AY2		PIN_D2
#define CROSSPOINT_AX0		PIN_D3
#define CROSSPOINT_AX1		PIN_D4
#define CROSSPOINT_AX2		PIN_D5
#define CROSSPOINT_AX3		PIN_D6
#define NC_D7				PIN_D7

#define	INITIAL_PORTD_VALUE	0b10000000
#define	INITIAL_TRISD_VALUE	0b10000000

#define CROSSPOINT_DATA		PIN_E0
#define CROSSPOINT_STROBE	PIN_E1
#define CROSSPOINT_RESET	PIN_E2

#define	INITIAL_PORTE_VALUE	0b00000000
#define	INITIAL_TRISE_VALUE	0b00000000

#use fast_io (A)
#use fast_io (B)
#use fast_io (C)
#use fast_io (D)
#use fast_io (E)


#define PS2_DATA_PORT		B
#define PS2_CLK_PORT		B
#define JOYSTICK_IO_PORT	A
